[package]
name = "position-settlement"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
common = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
fusdc = { path = "../fusdc" }
oracle-hub = { path = "../oracle-hub" }
rate-vamm = { path = "../rate-vamm" }
mock-pool = { path = "../mock-pool" }
strategy-adapter = { path = "../strategy-adapter" }
